title: "Portfólio Power BI"
description: "Meus dashboards embedados"
url: "https://hugomagrib.github.io/"   # opcional, mas bom pra SEO
# baseurl: ""                          # use caso esteja em subdiretório
